[project]
name = "DeskPilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.5",
    "google-generativeai>=0.8.0",
    "pillow>=10.0.0",
    "pyautogui>=0.9.54",
]
